### PR TITLE
Giphy UI improvements

### PR DESCRIPTION
**Pull request by Jasonvdb**
## Description

- Fix gif aspect ratio on add note view
- Use high res gem image on splash screen
- Fixed gif aspect ration on TX detail view
- Add note scroll view with keyboard behaviour improvements
- Changed position of Giphy attribution

## Motivation and Context

Related to https://github.com/tari-project/wallet-ios/issues/545
Related to https://github.com/tari-project/wallet-ios/issues/538
Related to https://github.com/tari-project/wallet-ios/issues/539

## How Has This Been Tested?

Manually

## Screenshots and/or video clip

Simulator Screen Shot - iPhone Xs 13 6 - 2020-08-11 at 13 55 00
Simulator Screen Shot - iPhone Xs 13 6 - 2020-08-11 at 13 19 44
Simulator Screen Shot - iPhone Xs 13 6 - 2020-08-11 at 13 55 24
Simulator Screen Shot - iPhone Xs 13 6 - 2020-08-11 at 13 55 39

## Types of changes

* [x] UI fix (non-breaking change which fixes a UI issue)
* [x] Functionality bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I have tested this on multiple simulator devices with different screensizes.
* [x] I'm merging against the `development` branch.
* [x] Commits have been squashed into one commit with a descriptive commit message
* [x] I ran all tests before pushing.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added/changed tests to cover my changes if not UI changes.

### CODE REVIEW

**Comment by kukabi** [comment]
Looking good in general, one thing:
IMG_8578

 Is there a quick fix for this?

**Comment by kukabi** [comment]
Would be good to remove the bottom inset in tx details table view too.
IMG_8579

**Comment by Jasonvdb** [comment]
> Would be good to remove the bottom inset in tx details table view too.
Cool, dropped the bottom inset by 100 points
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-11 at 15 52 25

**Comment by Jasonvdb** [comment]
> Is there a quick fix for this?

I hope so, trying to find it now

**Pull request merged**
