### PR TITLE
AES Encryption

### PR DESCRIPTION
**Pull request by SerhiiShovkoplias**
## Description
aes cbc encryption\decryption with initial vector + password salting
aes encription tests

## How Has This Been Tested?
manual testing

## Types of changes

* [ ] UI fix (non-breaking change which fixes a UI issue)
* [ ] Functionality bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I have tested this on multiple simulator devices with different screensizes.
* [x] I'm merging against the `development` branch.
* [x] Commits have been squashed into one commit with a descriptive commit message
* [x] I ran all tests before pushing.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added/changed tests to cover my changes if not UI changes.

### CODE REVIEW

**Comment by Jasonvdb** [comment]
@crypt0ginge will you also take a look at these encryption related PRs?

**Comment by Jasonvdb** [comment]
@SerhiiShovkoplias please add a unit test to `MobileWalletTests.swift` so @crypt0ginge can play with this

**Comment by crypt0ginge** [comment]
'withUnsafeMutableBytes' and 'withUnsafeBytes' deprecated.

**Comment by SerhiiShovkoplias** [comment]
> 'withUnsafeMutableBytes' and 'withUnsafeBytes' deprecated.

Yes, you are right. But `withUnsafeBytes<R>(…) and  `withUnsafeMutableBytes<R> are used here. xCode does not show warning right now.

**Pull request merged**
